image: docker:latest

services:
    - docker:dind

stages:
    - build image
    - test
    - deploy to registry

variables:
    CURRENT_VER: $IMAGE_NAME:latest

cache:
  paths:
  - node_modules/


before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
    - apk add --update nodejs npm
    - npm install
    - npm install react-scripts -g

build_image:
    stage: build image
    script:
        - npm run build
        - echo "$CURRENT_VER"
        - docker build -t $CURRENT_VER .

test_script:
    stage: test
    script:
        - npm run test
        - docker run $CURRENT_VER

release:
    stage: deploy to registry
    only:
        - tags
    script:
        - docker tag $CURRENT_VER
        - docker push $CURRENT_VER