image: docker:latest
services:
- docker:18.09-dind

stages:
    - build image
    - release registry

variables:
    CURRENT_VER: $IMAGE_NAME:$CI_COMMIT_REF_NAME
    LATEST_VER: $IMAGE_NAME:latest

cache:
  paths:
  - node_modules/

before_script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
    - apk add --update nodejs npm
    - npm install
    - npm install react-scripts -g
    
build_image:
    stage: build image
    only:
        - tags
    script:
        - npm run build
        - echo "$IMAGE_NAME:$CI_COMMIT_TAG"
        - docker build --pull -t $IMAGE_NAME:$CI_COMMIT_TAG .
        - docker push $IMAGE_NAME:$CI_COMMIT_TAG

release:
    stage: release registry
    only:
        - tags
    script:
        - docker pull $CURRENT_VER
        - docker tag $CURRENT_VER $LATEST_VER
        - docker push $LATEST_VER

deploy:
    stage: deploy to production
    only:
        - tags
    before_script:
        - apk --no-cache add openssh rsync
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - ssh-add <(echo "$SSH_PRIV_KEY")
        - ssh -p22 $DEPLOY_USER@$DEPLOY_HOST "sudo docker pull $LATEST_VER && docker service update --image $LATEST_VER covidtoday"
        