image: docker:latest
services:
- docker:18.09-dind

stages:
    - build image
    - test
    - deploy to registry

variables:
    CURRENT_VER: $IMAGE_NAME:$CI_COMMIT_REF_NAME
    LATEST_VER: $IMAGE_NAME:latest

cache:
  paths:
  - node_modules/

before_script:
    - apk add --update nodejs npm
    - npm install
    
build_image:
    stage: build image
    before_script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
        - npm install react-scripts -g
    script:
        - npm run build
        - echo "$CURRENT_VER"
        - docker build --pull -t $CURRENT_VER .
        - docker push $CURRENT_VER

test_script:
    stage: test
    before_script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
    script:
        - npm run test
        - docker pull $CURRENT_VER
        - docker run $CURRENT_VER

release:
    stage: deploy to registry
    only:
        - tags
    before_script:
        - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
    script:
        - docker pull $CURRENT_VER
        - docker tag $CURRENT_VER $LATEST_VER
        - docker tag $CURRENT_VER $IMAGE_NAME:$CI_COMMIT_TAG
        - docker push $LATEST_VER
        - docker push $IMAGE_NAME:$CI_COMMIT_TAG

