image: docker:latest
services:
- docker:18.09-dind

stages:
    - build image
    - release registry
    - deploy to production

variables:
    CURRENT_VER: $IMAGE_NAME:$CI_COMMIT_REF_NAME
    LATEST_VER: $IMAGE_NAME:latest

before_script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
    
build_image:
    stage: build image
    only:
        - tags
    script:
        - echo "$IMAGE_NAME:$CI_COMMIT_TAG"
        - docker build --pull -t $IMAGE_NAME:$CI_COMMIT_TAG .
        - docker push $IMAGE_NAME:$CI_COMMIT_TAG

release:
    stage: release registry
    only:
        - tags
    script:
        - docker pull $CURRENT_VER
        - docker tag $CURRENT_VER $LATEST_VER
        - docker push $LATEST_VER

deploy:
    stage: deploy to production
    # only:
    #     - tags
    before_script:
        - apk --no-cache add openssh
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        # - ssh-add <(echo "$PRIV_KEY")
        # - ssh-add <(echo "$PRIV_KEY")
        - sh -c "ssh-add <(echo '$PRIV_KEY')"
    script:
        - ssh -p22 $DEPLOY_USER@$DEPLOY_HOST "sudo docker pull $LATEST_VER && sudo docker service update --image $LATEST_VER covidtoday"
        